version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: gorelikspb/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  backend:
    image: gorelikspb/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - frontend
    env_file:
      - ./.env



  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - /docs/:/usr/share/nginx/html/api/docs 
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres_data:
  redoc: