# Generated by Django 4.2.5 on 2023-10-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Задайте цвет в формате hex (например, #RRGGBB)', max_length=7),
        ),
    ]
